//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sudoku.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sudoku.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 009805060706240300020000074600504013050010080190306002260000030007053609010702500
        ///009802010602710500070000068800305027020080090910207006150000040004021803060403900
        ///009301200017200040600040075100080067005907800730060002380010009050008620004605300
        ///706000500028034100010702080860900020000316000030007095050803010004620850002000907
        ///903000400041028900050401030470200090000819000080005026060103070008970650007000203
        ///700090001060070030400203007607000205001507400809000603200106009030080050500040002
        ///20130050003080 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Easy {
            get {
                return ResourceManager.GetString("Easy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 050000080700030002600204001001906300000070000008401500200509004900060005060000030
        ///007610803501200007030000000203009000009000300000500104000000080700004206102078400
        ///900020054500760000126000000000900703050000080807004000000000318000086002480090007
        ///500603002001004000000070030740090001008507400600030087050020000000100900900305006
        ///060500007000400029780300000070290105000000000109045060000003046830004000500002010
        ///720010040010020068030004000003905000600000002000206300000800090140050070080060035
        ///00000000009060 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Extreme {
            get {
                return ResourceManager.GetString("Extreme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 012300900070040300060901000000400080600203005090008000000704010005080060006002870
        ///025000030800001020900405800070080402000000000308090060001607009040800003030000580
        ///000206908840500007000001000054100079000000000320007510000800000900002086507904000
        ///000008200000740900634000500700809060010000090050602007002000719005073000008100000
        ///000810004800000569004000010000740006020109030900052000080000200531000007600075000
        ///004000080520000043001800950400027010000030000070680004089003100130000062040000300
        ///05409160002000 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Hard {
            get {
                return ResourceManager.GetString("Hard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 000000010400000000020000000000050407008000300001090000300400200050100000000806000
        ///000000010400000000020000000000050604008000300001090000300400200050100000000807000
        ///000000012000035000000600070700000300000400800100000000000120000080000040050000600
        ///000000012003600000000007000410020000000500300700000600280000040000300500000000000
        ///000000012008030000000000040120500000000004700060000000507000300000620000000100000
        ///000000012040050000000009000070600400000100000000000050000087500601000300200000000
        ///00000001205040 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Impossible {
            get {
                return ResourceManager.GetString("Impossible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на 030056000560090402007100530074002091000908000190400650049005100305020084000340020
        ///200010063170400080009706500008060210400802005027040800002109400040005096930080007
        ///602300800070500102090807030005074600430000019009610200020109040108002060004005301
        ///007401300012600080900070062800090073006302800320040006250010009060005420009203500
        ///000005487504020060800036500060710008209000705100089040008360004040070301713200000
        ///008021400920705000071080900630090705080000060409070012006050230000407098005210600
        ///56300400904190 [остаток строки не уместился]&quot;;.
        /// </summary>
        internal static string Normal {
            get {
                return ResourceManager.GetString("Normal", resourceCulture);
            }
        }
    }
}
